# Generated by Django 4.2.16 on 2024-10-03 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0012_detection_remove_answer_answer_image_answer_image1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detection',
            new_name='DetectionPost',
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='SimilarityComment',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='SimilarityPost',
        ),
    ]
