# Generated by Django 4.2.16 on 2024-10-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_rename_detection_detectionpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaritycomment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooments', to='pybo.similaritypost'),
        ),
    ]
