# Generated by Django 4.2.16 on 2024-10-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_alter_similaritycomment_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similaritycomment',
            old_name='question',
            new_name='post',
        ),
    ]
