# Generated by Django 4.2.16 on 2024-10-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_rename_question_similaritycomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaritycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pybo.similaritypost'),
        ),
    ]
