# Generated by Django 4.2.16 on 2024-10-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_alter_similaritycomment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectioncomment',
            old_name='detection',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='similaritycomment',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='similarity/a_image1/', verbose_name='a_image1'),
        ),
        migrations.AlterField(
            model_name='similaritycomment',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='similarity/a_image2/', verbose_name='a_image2'),
        ),
        migrations.AlterField(
            model_name='similaritypost',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='similarity/q_image1/', verbose_name='q_image1'),
        ),
        migrations.AlterField(
            model_name='similaritypost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='similarity/q_image2/', verbose_name='q_image2'),
        ),
    ]
