# Generated by Django 4.2.16 on 2024-10-08 01:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0017_rename_detection_detectioncomment_post_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetectionComment',
            new_name='DetectionCommentModel',
        ),
        migrations.RenameModel(
            old_name='DetectionPost',
            new_name='DetectionPostModel',
        ),
        migrations.RenameModel(
            old_name='SimilarityPost',
            new_name='SimilarityPostModel',
        ),
    ]
